name: Stylelint

on:
  push:
    branches:
      - main

jobs:
  css:
    name: CSS Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/themes/custom/stylelintexample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
  # If you do not need to lock down the Node version but can rely on the version
  # shipped with ubuntu-latest.
  simple:
    name: Simple Lint
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: web/themes/custom/stylelintexample
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
